title: Marcia Mondiale per la Pace e la Nonviolenza
description: il sito italiano della 2ª Marcia Mondiale per la Pace e la Nonviolenza - 2019/2020
show_downloads: false
google_analytics: UA-95775-27
theme: jekyll-theme-cayman

lang: it_IT

social:
  name: Marcia Mondiale per la Pace e la Nonviolenza
  links:
    - https://www.facebook.com/MarciaMondiale

google_site_verification: Qs4an_ySxbiLaE1Di-i56KYgGFQSRj71_z_QByeWcP0
